# Generated by Django 5.2.6 on 2025-09-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Davlat nomi')),
                ('name_uz', models.CharField(max_length=120, null=True, unique=True, verbose_name='Davlat nomi')),
                ('name_ru', models.CharField(max_length=120, null=True, unique=True, verbose_name='Davlat nomi')),
                ('name_en', models.CharField(max_length=120, null=True, unique=True, verbose_name='Davlat nomi')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Bosh sarlavha')),
                ('hero_title_uz', models.CharField(max_length=255, null=True, verbose_name='Bosh sarlavha')),
                ('hero_title_ru', models.CharField(max_length=255, null=True, verbose_name='Bosh sarlavha')),
                ('hero_title_en', models.CharField(max_length=255, null=True, verbose_name='Bosh sarlavha')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Qisqa matn')),
                ('hero_subtitle_uz', models.TextField(blank=True, null=True, verbose_name='Qisqa matn')),
                ('hero_subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Qisqa matn')),
                ('hero_subtitle_en', models.TextField(blank=True, null=True, verbose_name='Qisqa matn')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='hero/', verbose_name='Reklama video')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nom')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon_svg', models.TextField(help_text='SVG kodini joylashtiring', verbose_name='SVG ikona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon_svg', models.TextField(help_text='SVG kodini joylashtiring', verbose_name='SVG ikona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xizmatlar', to='core.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Xizmat kartasi',
                'verbose_name_plural': 'Xizmat kartalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nom')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Nom')),
                ('number', models.IntegerField(default=0, verbose_name='Son')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG ikona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistikalar', to='core.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Bosqich raqami')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('description_uz', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(null=True, verbose_name='Tavsif')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosqichlar', to='core.sitesettings', verbose_name='Sayt sozlamalari')),
            ],
            options={
                'verbose_name': 'Ish bosqichi',
                'verbose_name_plural': 'Ish bosqichlari',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Shahar nomi')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='Shahar nomi')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='Shahar nomi')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Shahar nomi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.country', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
                'unique_together': {('country', 'name'), ('country', 'name_en'), ('country', 'name_ru'), ('country', 'name_uz')},
            },
        ),
    ]
