# Generated by Django 4.2.13 on 2025-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Kattaroq qiymat – pastroqda.')),
                ('label', models.CharField(max_length=160)),
                ('value_int', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Ikonka nomi/SVG sinfi/URL', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Kattaroq qiymat – pastroqda.')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('iso2', models.CharField(blank=True, default='', max_length=2)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Kattaroq qiymat – pastroqda.')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('media', models.URLField(blank=True, help_text='Rasm/Youtube havolasi (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Kattaroq qiymat – pastroqda.')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Kattaroq qiymat – pastroqda.')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=130)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
    ]
