# Generated by Django 5.2.6 on 2025-09-27 07:09

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Kategoriya nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Narx kategoriyasi',
                'verbose_name_plural': 'Narx kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitals/', verbose_name='Bosh rasm')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hospitals/hero/', verbose_name='Hero rasm')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asos solingan yil')),
                ('bed_count', models.PositiveIntegerField(default=0, verbose_name='Umumiy o‘rinlar')),
                ('icu_bed_count', models.PositiveIntegerField(default=0, verbose_name='Reanimatsiya o‘rinlari')),
                ('operating_rooms_count', models.PositiveIntegerField(default=0, verbose_name='Operatsion xonalar')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ommabop')),
                ('infrastructure_details', ckeditor.fields.RichTextField(blank=True, verbose_name='Infratuzilma')),
                ('infrastructure_details_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Infratuzilma')),
                ('infrastructure_details_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Infratuzilma')),
                ('infrastructure_details_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Infratuzilma')),
                ('guest_house_details', ckeditor.fields.RichTextField(blank=True, verbose_name='Mehmonxona/Guest house')),
                ('guest_house_details_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mehmonxona/Guest house')),
                ('guest_house_details_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mehmonxona/Guest house')),
                ('guest_house_details_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mehmonxona/Guest house')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='core.city', verbose_name='Shahar')),
                ('specialties', models.ManyToManyField(blank=True, related_name='hospitals', to='core.specialty', verbose_name='Yo‘nalishlar')),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospitals/gallery/', verbose_name='Rasm')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinics.hospital', verbose_name='Shifoxona')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
            },
        ),
        migrations.CreateModel(
            name='HospitalTreatmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255, verbose_name='Muolaja nomi')),
                ('procedure_name_uz', models.CharField(max_length=255, null=True, verbose_name='Muolaja nomi')),
                ('procedure_name_ru', models.CharField(max_length=255, null=True, verbose_name='Muolaja nomi')),
                ('procedure_name_en', models.CharField(max_length=255, null=True, verbose_name='Muolaja nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (USD)')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.hospital', verbose_name='Shifoxona')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_prices', to='clinics.pricecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Shifoxona narxi',
                'verbose_name_plural': 'Shifoxona narxlari',
            },
        ),
    ]
