# Generated by Django 5.2.6 on 2025-09-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG ikona kodi')),
            ],
            options={
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True)),
                ('subtitle_uz', models.TextField(blank=True, null=True)),
                ('subtitle_ru', models.TextField(blank=True, null=True)),
                ('subtitle_en', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Xizmatlar bilan tanishish', max_length=120)),
                ('button_text_uz', models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True)),
                ('button_text_ru', models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True)),
                ('button_text_en', models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_uz', models.TextField(blank=True, null=True)),
                ('meta_description_ru', models.TextField(blank=True, null=True)),
                ('meta_description_en', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Service Intro',
                'verbose_name_plural': 'Service Intros',
            },
        ),
        migrations.CreateModel(
            name='JourneyStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('text_uz', models.CharField(max_length=500, null=True)),
                ('text_ru', models.CharField(max_length=500, null=True)),
                ('text_en', models.CharField(max_length=500, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.journeystep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
