# Generated by Django 5.2.6 on 2025-09-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeystep',
            options={'ordering': ['order', 'step_number'], 'verbose_name': 'Yo‘l bosqichi', 'verbose_name_plural': 'Yo‘l bosqichlari'},
        ),
        migrations.AlterModelOptions(
            name='journeystepitem',
            options={'ordering': ['order'], 'verbose_name': 'Bosqich elementi', 'verbose_name_plural': 'Bosqich elementlari'},
        ),
        migrations.AlterModelOptions(
            name='serviceintro',
            options={'verbose_name': 'Xizmat intro', 'verbose_name_plural': 'Xizmat introlar'},
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG ikona kodi', verbose_name='SVG ikona kodi'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='step_number',
            field=models.PositiveIntegerField(verbose_name='Bosqich raqami'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.journeystep', verbose_name='Bosqich'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='journeystepitem',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='button_text',
            field=models.CharField(default='Xizmatlar bilan tanishish', max_length=120, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='button_text_en',
            field=models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='button_text_ru',
            field=models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='button_text_uz',
            field=models.CharField(default='Xizmatlar bilan tanishish', max_length=120, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta kalit so‘zlar'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='subtitle_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
