# Generated by Django 5.2.6 on 2025-09-27 10:12

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog kategoriya',
                'verbose_name_plural': 'Blog kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Rasm')),
                ('summary', models.TextField(blank=True, verbose_name='Qisqa izoh')),
                ('summary_uz', models.TextField(blank=True, null=True, verbose_name='Qisqa izoh')),
                ('summary_ru', models.TextField(blank=True, null=True, verbose_name='Qisqa izoh')),
                ('summary_en', models.TextField(blank=True, null=True, verbose_name='Qisqa izoh')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Kontent')),
                ('content_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Kontent')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Kontent')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Kontent')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan sana')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan')], default='draft', max_length=10, verbose_name='Holat')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilandi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
