# Generated by Django 5.2.6 on 2025-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_of', models.CharField(max_length=255, verbose_name='Qayerdan')),
                ('treatment', models.CharField(max_length=255, verbose_name='Davolanish turi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', 'Ko‘rib chiqildi')], default='new', max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'So‘rov',
                'verbose_name_plural': 'So‘rovlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
