# Generated by Django 5.2.6 on 2025-09-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Bemor ismi')),
                ('patient_name_uz', models.CharField(max_length=255, null=True, verbose_name='Bemor ismi')),
                ('patient_name_ru', models.CharField(max_length=255, null=True, verbose_name='Bemor ismi')),
                ('patient_name_en', models.CharField(max_length=255, null=True, verbose_name='Bemor ismi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Rasm')),
                ('treatment_received', models.CharField(blank=True, max_length=255, verbose_name='Olingan davolanish')),
                ('treatment_received_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Olingan davolanish')),
                ('treatment_received_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Olingan davolanish')),
                ('treatment_received_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Olingan davolanish')),
                ('review_text', models.TextField(verbose_name='Sharh matni')),
                ('review_text_uz', models.TextField(null=True, verbose_name='Sharh matni')),
                ('review_text_ru', models.TextField(null=True, verbose_name='Sharh matni')),
                ('review_text_en', models.TextField(null=True, verbose_name='Sharh matni')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan (featured)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Mamlakat')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('bio_uz', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Mamlakat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
