# Generated by Django 5.2.6 on 2025-09-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='To‘liq ism')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='To‘liq ism')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='To‘liq ism')),
                ('specialty_title', models.CharField(max_length=255, verbose_name='Mutaxassislik (matn)')),
                ('specialty_title_uz', models.CharField(max_length=255, null=True, verbose_name='Mutaxassislik (matn)')),
                ('specialty_title_ru', models.CharField(max_length=255, null=True, verbose_name='Mutaxassislik (matn)')),
                ('specialty_title_en', models.CharField(max_length=255, null=True, verbose_name='Mutaxassislik (matn)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Rasm')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('rating', models.FloatField(default=0, verbose_name='Reyting')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('surgeries_count', models.PositiveIntegerField(default=0, verbose_name='Amaliyotlar soni')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ommabop')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='doctors/resumes/', verbose_name='Rezyume')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta tavsif')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta kalit so‘zlar')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('hospitals', models.ManyToManyField(blank=True, related_name='doctors', to='clinics.hospital', verbose_name='Klinikalar')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='core.specialty', verbose_name='Mutaxassislik (model)')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['-is_popular', 'full_name'],
            },
        ),
    ]
